# Generated by Django 5.1 on 2024-09-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_system', '0002_alter_room_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='verification_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
