# Generated by Django 5.1 on 2024-09-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_system', '0003_booking_is_verified_booking_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='location',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
